kind: Pod
apiVersion: v1
metadata:
  name: userservice-pod
  labels:
    myvalue: user-service                                # Label for applying service later
spec:
  containers:
    - name: user01
      image: chetangsanghi/kube-user-service:0.1
      ports:
       - containerPort: 8090                         # Expose port 8090 from container

